

INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('101000', '서울특별시', '101000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('101010', '강남구', '101000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('101020', '강동구', '101000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('101030', '강북구', '101000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('101040', '강서구', '101000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('101050', '관악구', '101000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('101060', '광진구', '101000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('101070', '구로구', '101000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('101080', '금천구', '101000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('101090', '노원구', '101000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('101100', '도봉구', '101000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('101110', '동대문구', '101000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('101120', '동작구', '101000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('101130', '마포구', '101000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('101140', '서대문구', '101000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('101150', '서초구', '101000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('101160', '성동구', '101000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('101170', '성북구', '101000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('101180', '송파구', '101000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('101190', '양천구', '101000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('101200', '영등포구', '101000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('101210', '용산구', '101000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('101220', '은평구', '101000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('101230', '종로구', '101000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('101240', '중구', '101000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('101250', '중랑구', '101000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('102000', '경기도', '102000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('102010', '가평군', '102000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('102020', '고양시', '102000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('102030', '고양시 덕양구', '102000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('102040', '고양시 일산동구', '102000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('102050', '고양시 일산서구', '102000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('102060', '과천시', '102000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('102070', '광명시', '102000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('102080', '광주시', '102000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('102090', '구리시', '102000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('102100', '군포시', '102000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('102110', '김포시', '102000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('102120', '남양주시', '102000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('102130', '동두천시', '102000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('102140', '부천시', '102000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('102150', '부천시 소사구', '102000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('102160', '부천시 오정구', '102000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('102170', '부천시 원미구', '102000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('102180', '성남시', '102000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('102190', '성남시 분당구', '102000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('102200', '성남시 수정구', '102000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('102210', '성남시 중원구', '102000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('102220', '수원시', '102000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('102230', '수원시 권선구', '102000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('102240', '수원시 영통구', '102000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('102250', '수원시 장안구', '102000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('102260', '수원시 팔달구', '102000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('102270', '시흥시', '102000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('102280', '안산시', '102000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('102290', '안산시 단원구', '102000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('102300', '안산시 상록구', '102000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('102310', '안성시', '102000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('102320', '안양시', '102000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('102330', '안양시 동안구', '102000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('102340', '안양시 만안구', '102000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('102350', '양주시', '102000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('102360', '양평군', '102000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('102370', '여주시', '102000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('102380', '연천군', '102000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('102390', '오산시', '102000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('102400', '용인시', '102000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('102410', '용인시 기흥구', '102000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('102420', '용인시 수지구', '102000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('102430', '용인시 처인구', '102000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('102440', '의왕시', '102000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('102450', '의정부시', '102000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('102460', '이천시', '102000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('102470', '파주시', '102000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('102480', '평택시', '102000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('102490', '포천시', '102000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('102500', '하남시', '102000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('102510', '화성시', '102000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('103000', '광주광역시', '103000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('103010', '광산구', '103000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('103020', '남구', '103000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('103030', '동구', '103000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('103040', '북구', '103000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('103050', '서구', '103000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('104000', '대구광역시', '104000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('104010', '남구', '104000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('104020', '달서구', '104000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('104030', '달성군', '104000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('104040', '동구', '104000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('104050', '북구', '104000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('104060', '서구', '104000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('104070', '수성구', '104000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('104080', '중구', '104000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('104090', '군위군', '104000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('105000', '대전광역시', '105000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('105010', '대덕구', '105000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('105020', '동구', '105000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('105030', '서구', '105000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('105040', '유성구', '105000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('105050', '중구', '105000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('106000', '부산광역시', '106000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('106010', '강서구', '106000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('106020', '금정구', '106000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('106030', '기장군', '106000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('106040', '남구', '106000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('106050', '동구', '106000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('106060', '동래구', '106000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('106070', '부산진구', '106000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('106080', '북구', '106000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('106090', '사상구', '106000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('106100', '사하구', '106000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('106110', '서구', '106000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('106120', '수영구', '106000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('106130', '연제구', '106000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('106140', '영도구', '106000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('106150', '중구', '106000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('106160', '해운대구', '106000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('107000', '울산광역시', '107000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('107010', '남구', '107000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('107020', '동구', '107000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('107030', '북구', '107000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('107040', '울주군', '107000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('107050', '중구', '107000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('108000', '인천광역시', '108000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('108010', '강화군', '108000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('108020', '계양구', '108000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('108030', '미추홀구', '108000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('108040', '남동구', '108000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('108050', '동구', '108000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('108060', '부평구', '108000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('108070', '서구', '108000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('108080', '연수구', '108000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('108090', '옹진군', '108000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('108100', '중구', '108000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('109000', '강원특별자치도', '109000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('109010', '강릉시', '109000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('109020', '고성군', '109000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('109030', '동해시', '109000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('109040', '삼척시', '109000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('109050', '속초시', '109000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('109060', '양구군', '109000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('109070', '양양군', '109000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('109080', '영월군', '109000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('109090', '원주시', '109000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('109100', '인제군', '109000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('109110', '정선군', '109000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('109120', '철원군', '109000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('109130', '춘천시', '109000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('109140', '태백시', '109000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('109150', '평창군', '109000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('109160', '홍천군', '109000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('109170', '화천군', '109000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('109180', '횡성군', '109000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('110000', '경상남도', '110000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('110010', '거제시', '110000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('110020', '거창군', '110000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('110030', '고성군', '110000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('110040', '김해시', '110000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('110050', '남해군', '110000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('110053', '창원시 마산회원구', '110000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('110055', '창원시 마산합포구', '110000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('110057', '창원시 성산구', '110000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('110059', '창원시 의창구', '110000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('110070', '밀양시', '110000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('110080', '사천시', '110000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('110090', '산청군', '110000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('110100', '양산시', '110000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('110110', '의령군', '110000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('110120', '진주시', '110000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('110130', '창원시 진해구', '110000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('110140', '창녕군', '110000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('110150', '창원시', '110000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('110160', '통영시', '110000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('110170', '하동군', '110000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('110180', '함안군', '110000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('110190', '함양군', '110000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('110200', '합천군', '110000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('111000', '경상북도', '111000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('111010', '경산시', '111000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('111020', '경주시', '111000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('111030', '고령군', '111000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('111040', '구미시', '111000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('111050', '군위군', '111000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('111060', '김천시', '111000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('111070', '문경시', '111000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('111080', '봉화군', '111000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('111090', '상주시', '111000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('111100', '성주군', '111000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('111110', '안동시', '111000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('111120', '영덕군', '111000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('111130', '영양군', '111000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('111140', '영주시', '111000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('111150', '영천시', '111000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('111160', '예천군', '111000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('111170', '울릉군', '111000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('111180', '울진군', '111000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('111190', '의성군', '111000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('111200', '청도군', '111000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('111210', '청송군', '111000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('111220', '칠곡군', '111000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('111230', '포항시', '111000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('111240', '포항시 남구', '111000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('111250', '포항시 북구', '111000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('112000', '전라남도', '112000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('112010', '강진군', '112000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('112020', '고흥군', '112000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('112030', '곡성군', '112000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('112040', '광양시', '112000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('112050', '구례군', '112000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('112060', '나주시', '112000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('112070', '담양군', '112000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('112080', '목포시', '112000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('112090', '무안군', '112000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('112100', '보성군', '112000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('112110', '순천시', '112000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('112120', '신안군', '112000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('112130', '여수시', '112000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('112140', '영광군', '112000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('112150', '영암군', '112000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('112160', '완도군', '112000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('112170', '장성군', '112000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('112180', '장흥군', '112000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('112190', '진도군', '112000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('112200', '함평군', '112000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('112210', '해남군', '112000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('112220', '화순군', '112000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('113000', '전북특별자치도', '113000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('113010', '고창군', '113000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('113020', '군산시', '113000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('113030', '김제시', '113000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('113040', '남원시', '113000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('113050', '무주군', '113000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('113060', '부안군', '113000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('113070', '순창군', '113000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('113080', '완주군', '113000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('113090', '익산시', '113000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('113100', '임실군', '113000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('113110', '장수군', '113000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('113120', '전주시', '113000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('113130', '전주시 덕진구', '113000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('113140', '전주시 완산구', '113000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('113150', '정읍시', '113000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('113160', '진안군', '113000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('114000', '충청북도', '114000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('114010', '괴산군', '114000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('114020', '단양군', '114000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('114030', '보은군', '114000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('114040', '영동군', '114000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('114050', '옥천군', '114000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('114060', '음성군', '114000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('114070', '제천시', '114000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('114080', '증평군', '114000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('114090', '진천군', '114000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('114100', '청원군', '114000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('114110', '청주시', '114000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('114120', '청주시 상당구', '114000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('114130', '청주시 흥덕구', '114000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('114140', '충주시', '114000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('114150', '청주시 청원구', '114000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('114160', '청주시 서원구', '114000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('115000', '충청남도', '115000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('115010', '계룡시', '115000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('115020', '공주시', '115000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('115030', '금산군', '115000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('115040', '논산시', '115000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('115050', '당진시', '115000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('115060', '보령시', '115000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('115070', '부여군', '115000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('115080', '서산시', '115000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('115090', '서천군', '115000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('115100', '아산시', '115000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('115110', '연기군', '115000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('115120', '예산군', '115000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('115130', '천안시', '115000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('115133', '천안시 동남구', '115000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('115135', '천안시 서북구', '115000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('115140', '청양군', '115000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('115150', '태안군', '115000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('115160', '홍성군', '115000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('116000', '제주특별자치도', '116000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('116030', '서귀포시', '116000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('116040', '제주시', '116000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('117000', '전국', '117000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
INSERT INTO `space`.sgg (sgg_cd, sgg_nm, uppr_cd, use_yn, reg_time, update_time, created_by, modified_by) VALUES('118000', '세종특별자치시', '118000', 'Y', now(), now(), 'SYSTEM', 'SYSTEM');
